# Generated by Django 4.0.1 on 2022-02-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_log_scrolldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('view_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.n_content')),
            ],
        ),
    ]
