# Generated by Django 4.0.1 on 2022-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitcountHitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField()),
                ('modified', models.DateTimeField()),
                ('object_pk', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'hitcount_hit_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memberinfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'memberinfo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
