# Generated by Django 4.0.1 on 2022-02-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_hitcounthitcount_memberinfo_delete_viewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitcountHitCount',
        ),
    ]
