# Generated by Django 4.0.1 on 2022-02-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_viewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
