# Generated by Django 4.0.1 on 2022-02-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_viewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewcount',
        ),
    ]
