# Generated by Django 4.0.1 on 2022-02-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_viewcount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.news'),
        ),
    ]
