# Generated by Django 4.0.1 on 2022-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsViewcount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='조회수')),
            ],
            options={
                'db_table': 'news_viewcount',
                'managed': False,
            },
        ),
    ]
