# Generated by Django 4.0.1 on 2022-02-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_viewcount_n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
