# Generated by Django 4.0.1 on 2022-02-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_newsviewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsViewcount',
        ),
    ]
