# Generated by Django 4.0.1 on 2022-02-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_delete_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(blank=True, default=0)),
                ('n', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.news')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.memberinfo')),
            ],
        ),
    ]
