# Generated by Django 4.0.1 on 2022-02-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_n_viewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='n_viewcount',
            options={'managed': False},
        ),
    ]
