# Generated by Django 4.0.1 on 2022-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_n_viewcount_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='n_viewcount',
            table='N_Viewcount',
        ),
    ]
