# Generated by Django 4.0.1 on 2022-02-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_nviewcount_remove_n_viewcount_hits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(default=0, null=True)),
                ('ip', models.ForeignKey(db_column='IPaddr', on_delete=django.db.models.deletion.DO_NOTHING, to='news.log')),
                ('n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.news')),
            ],
        ),
        migrations.DeleteModel(
            name='NViewcount',
        ),
    ]
