# Generated by Django 4.0.1 on 2022-02-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_n_view_delete_nviewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='N_view',
        ),
    ]
