# Generated by Django 4.0.1 on 2022-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_delete_n_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_Viewcount',
            fields=[
                ('v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=0, unique=True)),
            ],
            options={
                'db_table': 'N_Viewcount',
                'managed': False,
            },
        ),
    ]
