# Generated by Django 4.0.1 on 2022-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_delete_n_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_Viewcount',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'N_Viewcount',
                'managed': False,
            },
        ),
    ]
