# Generated by Django 4.0.1 on 2022-02-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_delete_n_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_Viewcount',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.news')),
                ('user', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.memberinfo')),
            ],
        ),
    ]
